version: "3.9"

services:
  web:
    image: ${IMAGE_REPO:-yourdockerhubuser/mgmt_v2}:latest
    env_file: .env.production
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    environment:
      # Optional tuning overrides
      PORT: "8000"
      WORKERS: "3"
      THREADS: "2"
      AUTO_MIGRATE: "true"
      AUTO_COLLECTSTATIC: "true"

volumes:
  static:
  media:
